blog/urls.py
from django.urls import path, include
from .views import my_view, post_list
from django.conf.urls import url
from . import views as s, views
from django.conf.urls.static import static
from django.conf import settings

from .views import (
    BlogDeleteView,
)

urlpatterns = [
    path('', my_view, name='my-view'),
    path('post/<int:pk>/', views.post_detail, name='post_detail'),
    path('author/<id>/', views.post_author, name = 'post_author'),
    path('my_site/', views.my_site, name = 'my_site'),
    path('post/<int:pk>/delete/', BlogDeleteView.as_view(), name='post_delete'),
    path('post/new/', views.post_new, name='post_new'),
    # path('post/<int:pk>/edit/', views.post_edit, name='post_edit'),
    path('accounts/', include('django.contrib.auth.urls')),
    path('signup', s.signup, name='signup'),


] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import url


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog.urls')),
]

blog/models.py
from django.db import models
from django.conf import settings
from django.utils import timezone
#User = settings.AUTH_USER_MODEL()



class Documents(models.Model):
    docfile = models.ImageField(upload_to='documents/%Y/%m/%d')
    text = models.TextField(null=True,blank=True)
    author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE,null=True)
    created_date = models.DateTimeField(default=timezone.now)

    class Meta:
        ordering = ['-created_date']


class Comments(models.Model):
    """Ксласс комментариев к новостям
    """
    user = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        verbose_name="Пользователь",
        on_delete=models.CASCADE)
    new = models.ForeignKey(
         Documents,
         verbose_name="Новость",
         on_delete=models.CASCADE)
    text = models.TextField("Комментарий")
    created = models.DateTimeField("Дата добавления", auto_now_add=True, null=True)
    moderation = models.BooleanField("Модерация", default=False)

    class Meta:
        verbose_name = "Комментарий"
        verbose_name_plural = "Комментарии"

    def __str__(self):
        return "{}".format(self.user)

blog/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

from blog.models import Documents
from .models import Comments
from django.forms import ModelForm


class SignUpForm(UserCreationForm):
    email = forms.EmailField(max_length=254, help_text='Это поле обязательно')

    class Meta:
        model = User
        fields = ('username', 'email', 'password1', 'password2',)


class DocumentForm(forms.ModelForm):
    docfile = forms.FileField(label='Select a file')

    class Meta:
        model = Documents
        fields = ('docfile', 'text',)


class CommentForm(ModelForm):

    class Meta:
        model = Comments
        fields = ('text', )

blog/views.py
from django.contrib.auth import login, authenticate
from django.contrib.auth.decorators import login_required
from django.shortcuts import get_object_or_404
from django.shortcuts import render, redirect
from django.utils import timezone
from django.views.generic.edit import CreateView, UpdateView, DeleteView # новое
from django.urls import reverse_lazy

from blog.forms import DocumentForm
from .forms import SignUpForm


from .models import Documents, Comments
from .forms import DocumentForm
from .forms import CommentForm



def my_view(request):
    print(f"Great! You're using Python 3.6+. If you fail here, use the right version.")
    message = 'Upload as many files as you want!'
    # Handle file upload
    if request.method == 'POST':
        form = DocumentForm(request.POST, request.FILES)
        if form.is_valid():
            newdoc = Documents(docfile=request.FILES['docfile'])
            author = request.user
            published_date = timezone.now()
            newdoc.save()

            # Redirect to the document list after POST
            return redirect('my-view')
        else:
            message = 'The form is not valid. Fix the following error:'
    else:
        form = DocumentForm()  # An empty, unbound form

    # Load documents for the list page
    documents = Documents.objects.all()

    # Render list page with the documents and the form
    context = {'documents': documents, 'form': form, 'message': message}
    return render(request, 'blog/post_list.html', context)




@login_required
def post_list(request):
    Document = Documents.objects.order_by('-created_date').all()
    return render(request, 'blog/post_list.html', {'Document': Document})


def post_author(request, id):
    user = Documents.objects.get(id=request.user.id)
    documents = Documents.objects.filter(id=request.user.id)
    return render(request, 'blog/post_author.html', {'documents': documents})


def my_site(request):
    context = {
        'posts': Documents.objects.filter(author=request.user)
    }
    return render(request, 'blog/my_site.html', context)


class BlogDeleteView(DeleteView):
    model = Documents
    template_name = 'blog/post_delete.html'
    success_url = reverse_lazy('my-view')



@login_required
def post_detail(request, pk):
    new = get_object_or_404(Documents, pk=pk)
    comment = Comments.objects.filter(pk=pk)
    if request.method == "POST":
        form = CommentForm(request.POST)
        if form.is_valid():
            form = form.save(commit=False)
            form.user = request.user
            form.new = new
            form.save()
            return redirect(post_detail, pk)
    else:
        form = CommentForm()
    return render(request, "blog/post_detail.html",
                  {"new": new,
                   "comments": comment,
                   "form": form})



#def post_edit(request, pk):
   # post = get_object_or_404(Documents, pk=pk)
    #if request.method == "POST":
       # #form = DocumentForm(request.POST)
       # form = DocumentForm(request.POST, request.FILES)
       # if form.is_valid():
           # form = form.save(commit=False)
           # Documents.author = request.user
           # Documents.published_date = timezone.now()
           # Documents.save()
           # return redirect('blog/post_list.html', pk=post.pk)
    #else:
       # form = DocumentForm()
    #return render(request, 'blog/post_edit.html', {'form': form})


def post_new(request):
    if request.method == "POST":
        form = DocumentForm(request.POST, request.FILES)
        if form.is_valid():
            post_new = form.save(commit=False)
            post_new.author = request.user
            post_new.save()
            return redirect('my-view')
    else:
        form = DocumentForm()
    return render(request, 'blog/post_edit.html', {'form': form})

def signup(request):
    if request.method == 'POST':
        form = SignUpForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            my_password = form.cleaned_data.get('password1')
            user = authenticate(username=username, password=my_password)
            login(request, user)
        return redirect('my-view')
    else:
        form = SignUpForm()
    return render(request, "registration/signup.html", {'form': form})

blog/templates/blog/base.html
{% load static %}
<html>
    <head>
        <title>InstagraN</title>
        <link href='http://fonts.googleapis.com/css?family=Lobster&subset=cyrillic,latin' rel='stylesheet' type='text/css'>
        <style type="text/css">
        header{
        height: 95px;
        display: flex;
        justify-content: space-between;
        align-items: center;

        }

        body{
        padding-left: 100px;
        padding-right: 100px;
        }

        nav a{
        font-family: 'Lobster';
        font-size: 20px;
        margin-right: 20px;
        color: black;
        text-decoration: none;
        }

        nav a:hover {
        text-decoration: underline;
        }

        nav1 a{
        font-family: 'Lobster';
        font-size: 30px;
        margin-right: 20px;
        color: 0F4FA8;
        text-decoration: none;
        }

        .post{
        display:flex;
        flex-direction: column;
        align-items: center;
        justify-content: center;

        }





        </style>
    </head>
    <body>
        <header>
            <div>
                <nav1><h1><a href="/">InstagraN</a></h1></nav1>
            </div>
            <div>
                <nav><a href="{% url 'my_site'%}">Моя страница</a></nav>
            </div>
            <div>
                {% if user.is_authenticated %}
                    <nav>Привет {{ user.get_username }}</nav>
                    <nav><a href="{% url 'logout'%}?next={{request.path}}">Выйти</a></nav>
            </div>
            {% else %}
            <div>
                    <nav><a href="{% url 'login'%}?next={{request.path}}">Войти</a></nav>
                {% endif %}
            </div>
        </header>
    <div>
        <div>
            {% if user.is_authenticated %}
            <button><nav><a href="{% url 'post_new' %}">Новая запись</a></nav></button>
            {% else %}
            <h1>Вы не можете делать посты пока не зарегестрируетесь</h1>
            {% endif %}
            </nav>
        </div>
        <div class="post">
            {% block content %}
            {% endblock %}
        </div>
    </div>
    </body>


</html>

blog/templates/blog/index.html
{% load static %}
<html>
    <head>
        <title>InstagraN</title>
        <link href='http://fonts.googleapis.com/css?family=Lobster&subset=cyrillic,latin' rel='stylesheet' type='text/css'>
        <style type="text/css">
        header{
        height: 95px;
        display: flex;
        justify-content: space-between;
        align-items: center;

        }

        body{
        padding-left: 100px;
        padding-right: 100px;
        }

        nav a{
        font-family: 'Lobster';
        font-size: 20px;
        margin-right: 20px;
        color: black;
        text-decoration: none;
        }

        nav a:hover {
        text-decoration: underline;
        }

        nav1 a{
        font-family: 'Lobster';
        font-size: 30px;
        margin-right: 20px;
        color: 0F4FA8;
        text-decoration: none;
        }

        .post{
        display:flex;
        flex-direction: column;
        align-items: center;
        justify-content: center;

        }





        </style>
    </head>
    <body>
        <header>
            <div>
                <nav1><h1><a href="/">InstagraN</a></h1></nav1>
            </div>
            <div>
                <nav><a href="{% url 'my_site'%}">Моя страница</a></nav>
            </div>
            <div>
                {% if user.is_authenticated %}
                    <nav>Привет {{ user.get_username }}</nav>
                    <nav><a href="{% url 'logout'%}?next={{request.path}}">Выйти</a></nav>
            </div>
            {% else %}
            <div>
                    <nav><a href="{% url 'login'%}?next={{request.path}}">Войти</a></nav>
                {% endif %}
            </div>
        </header>
    <div>
        <div>
            {% if user.is_authenticated %}
            <button><nav><a href="{% url 'post_new' %}">Новая запись</a></nav></button>
            {% else %}
            <h1>Вы не можете делать посты пока не зарегестрируетесь</h1>
            {% endif %}
            </nav>
        </div>
        <div class="post">
            {% block content %}
            {% endblock %}
        </div>
    </div>
    </body>


</html>

blog/templates/blog/my_site.html
{% extends 'blog/index.html' %}

{% block content %}
    {% for post in posts %}
        <p>{{ post.author }}</p>
        <p>{{ post.text }}</p>
        <p><img src="{{ post.docfile.url }}" alt=""></p>
    {% endfor %}
{% endblock %}

blog/templates/blog/post_author.html
{% extends 'blog/index.html' %}

{% block content %}
    {% for document in documents %}
        <p>{{ document.author }}</p>
        <p>{{ document.text }}</p>
        <p><img src="{{ document.docfile.url }}" alt=""></p>
    {% endfor %}
{% endblock %}

blog/templates/blog/post_delete.html
{% extends 'blog/index.html' %}
 
{% block content %}
<dev>
    <h1>Delete post</h1>
    <form action="" method="post">{% csrf_token %}
      <p>Вы уверены что хотите улалить запись?</p>
      <button><input type="submit" value="Подтвердить" /></button>
    </form>
</dev>
{% endblock content %}

blog/templates/blog/post_detail.html
{% extends 'blog/index.html' %}

{% block content %}

<div>
        {% if user.is_authenticated %}
        <p><a href="{% url 'post_delete' new.pk %}"> - удалить пост</a></p>
        {% endif %}
        <p class="fig"><img src="{{ new.docfile.url }}" width="400" height="400" alt=""></p>
        <p class="fig">{{ new.text }}</p>

    <p class="fig"><a href="{% url 'post_author' id=request.user.id  %}">{{ new.author }}</a></p>
    <p><img src="{{ document.docfile.url }}" alt=""></p>

    <div class="fig">
        <h4>Комментарии</h4>
     {% for comment in comments %}
         Пользователь - {{ comment.user }}<br>
         {{ comment.text }} <br>
         Добавлен - {{ comment.created }}<br><br>
     {% endfor %}
      {% for comment in new.comments_set.all %}
        Пользователь - {{ comment.user }}<br>
        {{ comment.text }} <br>
        Добавлен - {{ comment.created }}<br><br>
    {% endfor %}
    {% if user.is_active %}
        <form action="" method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit">Отправить</button>
        </form>
    {% else %}
        <h4>Что бы оставить комментарий авторизуйтесь</h4>
    {% endif %}

{% endblock %}
</div>
</div>

blog/templates/blog/post_edit.html
{% extends 'blog/index.html' %}

{% block content %}
    <h1>Опубликовать пост</h1>
        <form action="{% url 'post_new' %}" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            <p>
                {{ form.docfile }}
                {{ form.text }}
            </p>
            <p><input type="submit" value="Опубликовать"/></p>
        </form>

{% endblock %}

blog/templates/blog/post_list.html
{% extends 'blog/index.html' %}
{% load static %}

{% block content %}


        {% if documents %}
            <ul>
                <div class="col-md-8"></div>
                {% for document in documents %}

                <li><a href="{% url 'post_detail' pk=document.id %}"><img src="{{ document.docfile.url }}" width="400" height="400" alt=""></a></li>
                 <p>{{ document.text }}</p>
                 <p>{{ document.author }}</p>
                 <p>{{ document.created_date }}</p>
                {% endfor %}
                </div>
            </ul>
        {% else %}
            <p>Нет ни одного поста.</p>
        {% endif %}


{% endblock %}